name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio: ^5.4.2+1
  go_router: ^13.2.0
  permission_handler: ^11.0.1
  location: ^5.0.3
  ionicons: ^0.2.2
  intl: ^0.19.0
  awesome_notifications: ^0.9.3+1
  lottie: ^3.1.2
  google_mobile_ads: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
